spring.application.name=demo
# Server
server.port=8080

# DataSource (Supabase Postgres)
spring.datasource.url=jdbc:postgresql://db.cytyozzbxbwcacddlacq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=7ayFWjfNeFjTrFNn
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase Auth
supabase.auth.url=https://cytyozzbxbwcacddlacq.supabase.co/auth/v1
supabase.auth.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dHlvenpieGJ3Y2FjZGRsYWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MzkzNDcsImV4cCI6MjA4NDQxNTM0N30.oT73Sg20tDonSSQtpPbmlBhQBJwH1JLH82aSurYj5M4
supabase.jwt.secret=gLQL6kgERtdRuCZYEpQhJphA1DSJNFXCvhFznyh+Kfd9o/UHbKS9cx9/v6SV5dXGNzWfxGlZMKlp5KWGBu++Bw==

# Reset password url
app.frontend.reset-password-url=http://localhost:5173/reset-password

# Your Spring Boot JWT
jwt.secret=my-very-long-secret-key-change-this-to-at-least-32-chars
jwt.expiration=86400000  # 24 hours in ms

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/swagger-ui.html